### ISSUE TITLE
[Custom Filtered Deck From Browser Add On] Filtered deck shows cards that I have already reviewed

### ISSUE THREAD

**Issue by doulovetrees** [glutanimate/anki-addons-misc#126]
## Which add-on is affected? Custom Filtered Deck From Browser 

[ Please mention the add-on in the issue title as follows: "[Add-on name] My issue" ]

## Prerequisite checklist

[ Please enter an [ x ] character to confirm the points below: ]

- [x ] In case of a bug: Have you tried restarting Anki?
- [x ] Are you running the latest version of the add-on? Have you redownloaded the add-on from AnkiWeb to make sure?
- [x] Did you check the add-on description on AnkiWeb for known issues?
- [x] Did you perform a cursory search through existing issue reports?

## What is the problem/feature you would like to see fixed/implemented?
I was trying to create a custom filtered deck with NEW cards with two specific tags, but it keeps pulling cards that are due in the future and only a couple new cards. For ex: I set it to "is:new", 100 cards, but it will show me 80 review cards and 20 new ones only.  The number varies, ex: 51, 49, etc.

[ Please be as specific as possible. Provide screenshots if you think they can help. ]

## How can we reproduce the problem?
Not sure, but this problem occurs when I select two tags. If I select one tag to make a filtered deck and want 100 cards, I have no problem getting 100 new cards. The problem is when I select two tags.

[ What were you doing when the problem occurred? ]

1. Select two tags to make filtered deck from browser 
2. Typed in "is:new" and deleted "is:due"
3. Set limit to 100 
4. Cards selected to "Random"
5. Reschedule box checked. 

**Expected behavior:** [ What you expected to happen ]
Since I limited my cards to 100 and typed "is:new" I expected 100 new cards, not 80 review cards and 20 new cards. This combination of review and new cards will vary with the limit I set.

**Actual behavior:** [ What actually happened ]
See above. I don't get the new cards I asked for 

**Reproducible?:** [ Can you reliably reproduce the issue by following the steps above? ]
Yes

## Version information

**Anki** 2.1.22

[ Please head to *Help* → *About Anki* and Paste the version string here, e.g.: ]

Version 2.1.22 (0ecc189a)
Python 3.8.0 Qt 5.14.1 PyQt 5.14.1

**System**

- Operating system: [ Windows]
- Version: [10]

**Comment by anki876** [comment]
Any solution to this problem? I am on a mac and currently having the same exact issue

**Comment by glutanimate** [comment]
Thanks for the reports, guys. Please note that the add-on uses Anki's built in filtered deck creation dialog, so as soon as that dialog pops up, you're pretty much looking at how Anki behaves by default (not something specific to the add-on).

I assume the problem you're facing is due to the search phrase you're using. The add-on will simply copy over the search phrase that's currently seen in the browser's search bar, and Anki will then add `is:due`.

That means that, if you are limiting your search by multiple criteria - e.g. multiple tags -, you might have to add parentheses and/or keywords like `AND` / `OR` depending on what exactly you're looking for.

Here are a few examples:

New cards that have both the tag `hello` and `world`

    tag:hello tag:world is:new

New cards that either have the tag `hello` or `world`:

    (tag:hello OR tag:world) is:new

Cards in a specific deck that have either the `hello` or `world` tag, and are due:

     (tag:hello OR tag:world) deck:my_deck is:due

For more information on how Anki's query language works please see the manual section on searching here: https://docs.ankiweb.net/#/searching

Hope that helps!

Closing this issue report as it's not specific to the add-on.

Thanks again for taking the time to report this.
