### ISSUE TITLE
Updating an addon for 2.1?

### ISSUE THREAD

**Issue by mnhende2** [glutanimate/anki-addons-misc#15]
Glutanimate,

Greetings!  mnhende2 here.  

Curious is you have plans to update this addon for 2.1?
(https://github.com/glutanimate/anki-addons-misc/blob/master/src/reviewer_hint_hotkeys.py)

I've written Ben (the original author) multiple times, but he has never written back.  I assume he has discontinued his use of Anki.  I use the addon all the time in 2.0, so just hoping that someone will update it for 2.1.  

Take care!

**Comment by glutanimate** [comment]
Hey mnhende2,

Thanks for letting me know. I've reworked the add-on from the ground up in 31053b42fa8305e298e9c1610ea5ad45dd4fd1bd. It should now be compatible both with Anki 2.0 and 2.1.

I've refrained from uploading my version to AnkiWeb up to this point because I wanted to avoid having yet another instance of a duplicated add-on, but seeing how Ben hasn't been active in a while now, I have created a new add-on listing here: https://ankiweb.net/shared/info/1844908621

If you're interested in following the progress of my other add-ons: From now on I will be listing the current compatibility status in [this document](https://github.com/glutanimate/anki-addons-misc/blob/master/docs/anki21.md).

No guarantees as to any conversion time-frame, though. I'm not using 2.1 myself and won't be using it for the foreseeable future. Because of that and a general shortage of time, I will have to assign a low-priority to all non-trivial conversion tasks. Converting this add-on was still relatively easy, but a lot of the other add-ons in this repo will require a lot of effort to transition to 2.1 (and that's still nothing compared to the effort required to convert things like Image Occlusion or Cloze Overlapper..).

**Comment by aleksejrs** [comment]
The fix broke the addon for 2.0.47 on Debian stable with `pyqt4-dev-tools` 4.11.4+dfsg-1+b3:

```
  File "…/Anki2/addons/tagedit_subtag_completer.py", line 55, in paint
    if options.widget is None:
AttributeError: 'QStyleOptionViewItem' object has no attribute 'widget'
```

**Comment by glutanimate** [comment]
@aleksejrs That was a different commit (86014049e3e2414605ec147c27ba362bc818c9c3), but thanks for letting me know either way. A fix is on the way.

**Comment by aleksejrs** [comment]
@glutanimate, thanks, it works, also with highlighting on 2.1.

**Comment by mnhende2** [comment]
Thanks Glutanimate!  I'll start testing it out today.  Also, wishing you
well when you do get time to transition into 2.1  I've mostly made the
transition.  Though still using 2.0 for some things.

On Wed, Aug 23, 2017, at 03:40 PM, Aristotelis wrote:
> Hey mnhende2,


> Thanks for letting me know. I've reworked the add-on from the ground
> up in 31053b4. It should now be compatible both with Anki 2.0 and 2.1.> I've refrained from uploading my version to AnkiWeb up to this point
> because I wanted to avoid having yet another instance of a duplicated
> add-on, but seeing how Ben hasn't been active in a while now, I have
> created a new add-on listing here:
> https://ankiweb.net/shared/info/1844908621> If you're interested in following the progress of my other add-ons:
> From now on I will be listing the current compatibility status in this
> document[1].> No guarantees as to any conversion time-frame, though. I'm not using
> 2.1 myself and won't be using it for the foreseeable future. Because
> of that and a general shortage of time, I will have to assign a low-
> priority to all non-trivial conversion tasks. Converting this add-on
> was still relatively easy, but a lot of the other add-ons in this repo
> will require a lot of effort to transition to 2.1 (and that's still
> nothing compared to the effort required to convert things like Image
> Occlusion or Cloze Overlapper..).> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[2], or mute the thread[3].> 


Links:

  1. https://github.com/glutanimate/anki-addons-misc/blob/master/docs/anki21.md
  2. https://github.com/glutanimate/anki-addons-misc/issues/15#issuecomment-324334884
