### ISSUE TITLE
Search and Replace Tags >> Auto-complete doesn't show all available tags

### ISSUE THREAD

**Issue by axelboc** [Glutanimate/anki-addons-misc#3]
In the "Change tag" dialog, the auto-complete feature only shows the tags of the selected card (or of the card that was first selected when dealing with multiple cards). If I try to type the name of another tag in my collection, it doesn't show up in the list. This behaviour differs from Anki's tag inputs (e.g. in the "Add tags" dialog).

**Comment by Glutanimate** [comment]
Yes, that's by design. Ideally the add-on would autocomplete with the tags of all selected cards, but that would cause significant performance problems with larger selections. As it stands, having the add-on autocomplete on the tags of the first selected card is a good compromise I think. It should cover most use cases. If a user is going to batch-edit tags across multiple notes, the relevant tags will likely be present on most notes. Other tags can still be typed manually.

**Comment by axelboc** [comment]
Fair enough. Awesome add-on(s), by the way!
