### ISSUE TITLE
[Refocus Card when Reviewing] this add-on disables Enter

### ISSUE THREAD

**Issue by omega3** [glutanimate/anki-addons-misc#59]
Thank you very much to react so quickly. This add-on should be a default Anki behaviour. So, I am very grateful and a lot of other users will be. 

## Which add-on is affected?
Refocus Card when Reviewing

## Prerequisite checklist

- [x ] In case of a bug: Have you tried restarting Anki? 
- [x ] Are you running the latest version of the add-on? Have you redownloaded the add-on from AnkiWeb to make sure?
- [x ] Did you check the add-on description on AnkiWeb for known issues?
- [ ] Did you perform a cursory search through existing issue reports?
Not applicable. 

## What is the problem/feature you would like to see fixed/implemented?

When I use this add-on Enter function is disabled. Show answer and answer default proceeding to next card by hitting Enter both in main keyboard area and numeric keyboard area doesn't work. Only Space does that.

**Expected behaviour:** [ What you expected to happen ]

Both Enter keys should work normally with this add-on. 

**Actual behavior:** [ What actually happened ]
Enter doesn't work.

**Reproducible?:** [ Can you reliably reproduce the issue by following the steps above? ]
Always. I disabled add-on, restarted Anki and Enter worked. I enabled add-on and Enter didn't work again.

Maybe it conflicts with other add-ons. I don't know. I can provide you with a list of add-ons that I use. But Enter worked normally until I installed this add-on.

## Version information
Anki Version 2.1.4, Qt 5.9.2 PyQt 5.9 on Manjaro Linux Plasma 5.13.5, QT 5.11.1

**Comment by glutanimate** [comment]
Hi,

Thanks for the detailed report. This is listed as one of the limitations of the add-on in the description.

The internal behavior of the Enter key changed between 2.0 and 2.1. On 2.0 Enter was explicitly bound to revealing the answer. This is no longer the case with 2.1. Here Enter to show the answer only works as a side effect of the "Show answer" button being focused by default, and as the add-on switches focus away from the button it can no longer reveal the answer.

Implementing support for Return to  reveal the answer would entail manually assigning it to that answer which might interfere with typing support and other areas. So this is not entirely trivial, I'm afraid.

I might look into this again in the future, but for now I have to put this on hold given other tasks with higher priority. If anyone feels like tackling this, I'd be more than happy to accept a PR!

**Comment by glutanimate** [comment]
Please scratch what I said above. I forgot that I still had the [Customize Keyboard Shortcuts add-on](https://ankiweb.net/shared/info/24411424) installed from a previous add-on test run.

As it turns out, the Return key actually does work properly as long as either Customize Keyboard Shortcuts or Refocus Card are installed alone. It's only when both add-ons are installed that the Return key stops working properly.

In fact, if you just install Customize Keyboard Shortcuts, and then click on the card area you will see that the Return hotkey also stops working. So this is likely an issue in how keyboard shortcuts are reassigned using that add-on.

Closing this issue as it doesn't appear to be a problem with Refocus cards.
