### ISSUE TITLE
[Speed Focus Mode] "Automatically rate again" value exceeded by program

### ISSUE THREAD

**Issue by sarahlippinc** [glutanimate/anki-addons-misc#70]
I am using Anki 2.1 

Automatically rate 'again' after 10 seconds ignored.  Program counts to 20 and then shows next card.  I tried changing the setting to different seconds and the program does not use the inputted value and instead uses some other value.

**Comment by gajewsk2** [comment]
I am on 2.0 and can confirm that the auto fail does not seem work for me either.

**Comment by gajewsk2** [comment]
Also it seems to have a memory leak, where if you leave your anki on for too long the timer will stop even working until you restart

**Comment by glutanimate** [comment]
Thanks for the reports, guys.

However, I can't reproduce these issues on Anki 2.0 nor on 2.1. A few thoughts:

- @sarahlippinc, are you sure the cards you experienced this on were part of same deck options group? The add-on always uses the deck options group associated with a particular card. In case of reviewing, say, a parent deck with cards drawn from multiple subdecks, each subdeck's options group will be followed. My advice would be to double-check whether you have different add-on settings set up for different (sub)decks.

   Another thought: The "rate again" timer starts counting from the answer side. I.e.: If you have a 10 sec "show answer" timer set up, and a 10 sec "rate again" timer it will take 20 seconds in total until the next card is drawn up (without any user interaction)

- @gajewsk2, Please make sure that there are no other add-ons interfering with Speed Focus Mode. You might be aware of this, but the Reviewer is "highly contested territory" for add-on developers, and due to the way a lot of its web elements are implemented in 2.0 it's highly predispositioned towards add-on conflicts.

    My recommendation would be to try to disable individual add-ons on a case by case series in order to identify potential candidate add-ons (most important suspects of course being add-ons that target the Reviewer and/or apply global changes, e.g. Night Mode).

    Also: Along the same lines as mentioned above, "rate again" will only engage once the answer is revealed. If you haven't set up an "show answer" timer then you will have to reveal the answer side manually for the timer to start counting.

**Comment by glutanimate** [comment]
Closing this for now due to lack of activity, but please feel free to chime in again at any point if you run into this again.
